/**
 * Single source of truth: all backend error codes.
 *
 * The frontend files [src/lib/i18n/locales/tr/errors.json] and
 * [en/errors.json] are kept in sync with this enum. Whenever a new error
 * code is added here the corresponding i18n key MUST be added on the
 * frontend as well.
 *
 * CLAUDE.md rule: "All messages must be returned from the backend as
 * error codes; the frontend translates them." This enum is the
 * implementation of that rule.
 *
 * Naming convention:
 *   <DOMAIN>_<ACTION>_<REASON>
 *   e.g. TENANT_CONTEXT_MISSING, ENTITY_NOT_FOUND, USER_EMAIL_DUPLICATE
 */
export const ErrorCode = {
  // ── Tenant ──
  TENANT_CONTEXT_MISSING: 'TENANT_CONTEXT_MISSING',
  TENANT_FORBIDDEN: 'TENANT_FORBIDDEN',

  // ── Generic entity ──
  ENTITY_NOT_FOUND: 'ENTITY_NOT_FOUND',
  CODE_DUPLICATE: 'CODE_DUPLICATE',

  // ── Production (supplier production tracking) ──
  SUPPLIER_PRODUCTION_ORDER_NOT_FOUND: 'SUPPLIER_PRODUCTION_ORDER_NOT_FOUND',
  PRODUCTION_MILESTONE_NOT_FOUND: 'PRODUCTION_MILESTONE_NOT_FOUND',
  QUALITY_CHECK_NOT_FOUND: 'QUALITY_CHECK_NOT_FOUND',

  // ── Logistics (unified shipments) ──
  SHIPMENT_NOT_FOUND: 'SHIPMENT_NOT_FOUND',
  SHIPMENT_DIRECTION_INVALID: 'SHIPMENT_DIRECTION_INVALID',
  SHIPMENT_ORDER_REFERENCE_REQUIRED: 'SHIPMENT_ORDER_REFERENCE_REQUIRED',
  SHIPMENT_LEG_NOT_FOUND: 'SHIPMENT_LEG_NOT_FOUND',
  CARRIER_PAYMENT_NOT_FOUND: 'CARRIER_PAYMENT_NOT_FOUND',
  CONTAINER_EVENT_NOT_FOUND: 'CONTAINER_EVENT_NOT_FOUND',
  CUSTOMS_DECLARATION_NOT_FOUND: 'CUSTOMS_DECLARATION_NOT_FOUND',
  FREIGHT_QUOTE_NOT_FOUND: 'FREIGHT_QUOTE_NOT_FOUND',

  // ── Accounting (landed cost) ──
  LANDED_COST_CALCULATION_NOT_FOUND: 'LANDED_COST_CALCULATION_NOT_FOUND',
  LANDED_COST_PURCHASE_ORDER_EMPTY: 'LANDED_COST_PURCHASE_ORDER_EMPTY',
  LANDED_COST_QUANTITY_ZERO: 'LANDED_COST_QUANTITY_ZERO',

  // ── Inventory ──
  INVENTORY_CUT_QUANTITY_INVALID: 'INVENTORY_CUT_QUANTITY_INVALID',
  GOODS_RECEIVE_NOT_FOUND: 'GOODS_RECEIVE_NOT_FOUND',
  GOODS_RECEIVE_LINE_NOT_FOUND: 'GOODS_RECEIVE_LINE_NOT_FOUND',
  SUPPLIER_CLAIM_NOT_FOUND: 'SUPPLIER_CLAIM_NOT_FOUND',
  SUPPLIER_CLAIM_NO_DISCREPANCY: 'SUPPLIER_CLAIM_NO_DISCREPANCY',
  SUPPLIER_CLAIM_ALREADY_OPEN: 'SUPPLIER_CLAIM_ALREADY_OPEN',

  // ── IAM (roles) ──
  ROLE_SYSTEM_DELETE_FORBIDDEN: 'ROLE_SYSTEM_DELETE_FORBIDDEN',
  ROLE_SYSTEM_UPDATE_FORBIDDEN: 'ROLE_SYSTEM_UPDATE_FORBIDDEN',

  // ── Auth ──
  AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  AUTH_ACCOUNT_DEACTIVATED: 'AUTH_ACCOUNT_DEACTIVATED',
  AUTH_USER_NOT_FOUND_FOR_IMPERSONATION:
    'AUTH_USER_NOT_FOUND_FOR_IMPERSONATION',

  // ── Users ──
  USER_EMAIL_DUPLICATE: 'USER_EMAIL_DUPLICATE',
  USER_TENANT_OWNER_DELETE_FORBIDDEN: 'USER_TENANT_OWNER_DELETE_FORBIDDEN',

  // ── Picking / Packing (Sprint 10) ──
  PICKING_NOT_FOUND: 'PICKING_NOT_FOUND',
  PICKING_ALREADY_EXISTS: 'PICKING_ALREADY_EXISTS',
  PICKING_NOT_IN_PROGRESS: 'PICKING_NOT_IN_PROGRESS',
  PICKING_INCOMPLETE: 'PICKING_INCOMPLETE',
  SALES_ORDER_NOT_ALLOCATED: 'SALES_ORDER_NOT_ALLOCATED',
  KARTELA_NOT_FOUND_FOR_ORDER: 'KARTELA_NOT_FOUND_FOR_ORDER',
  KARTELA_ALREADY_PICKED: 'KARTELA_ALREADY_PICKED',
  PACKING_NOT_FOUND: 'PACKING_NOT_FOUND',
  PACKING_NOT_IN_PROGRESS: 'PACKING_NOT_IN_PROGRESS',
  PACKING_BOX_NOT_FOUND: 'PACKING_BOX_NOT_FOUND',
  PICKING_LINE_ALREADY_BOXED: 'PICKING_LINE_ALREADY_BOXED',
  PICKING_LINE_NOT_IN_PICKING: 'PICKING_LINE_NOT_IN_PICKING',

  // ── Impersonate (Sprint 19) ──
  IMPERSONATE_NO_USERS: 'IMPERSONATE_NO_USERS',

  // ── Outbound shipment / delivery (Sprint 10) ──
  SALES_ORDER_NOT_PACKED: 'SALES_ORDER_NOT_PACKED',
  OUTBOUND_SHIPMENT_ALREADY_EXISTS: 'OUTBOUND_SHIPMENT_ALREADY_EXISTS',
  DELIVERY_PROOF_ALREADY_RECORDED: 'DELIVERY_PROOF_ALREADY_RECORDED',
  DELIVERY_PROOF_SIGNATURE_REQUIRED: 'DELIVERY_PROOF_SIGNATURE_REQUIRED',
  SHIPMENT_NOT_SHIPPED: 'SHIPMENT_NOT_SHIPPED',
} as const;

export type ErrorCodeType = (typeof ErrorCode)[keyof typeof ErrorCode];
