import { Injectable } from '@nestjs/common';
import { JwtService } from '@nestjs/jwt';

/**
 * Payload embedded in a supplier portal JWT (Sprint 11).
 *
 * The supplier does not have a User row — instead they hold a signed
 * token that encodes their Partner id + tenant. Tokens have a 90-day
 * lifetime and are regenerated by the admin via
 * `SupplierTokenManagementDialog`.
 */
export interface SupplierTokenPayload {
  sub: string; // partner id
  tenantId: string;
  email?: string;
  kind: 'supplier-portal';
}

@Injectable()
export class SupplierPortalTokenService {
  constructor(private readonly jwt: JwtService) {}

  /** Issue a token valid for `days` (default 90). */
  issue(
    partnerId: string,
    tenantId: string,
    email?: string,
    days = 90,
  ): string {
    const payload: SupplierTokenPayload = {
      sub: partnerId,
      tenantId,
      email,
      kind: 'supplier-portal',
    };
    return this.jwt.sign(payload, { expiresIn: `${days}d` });
  }

  verify(token: string): SupplierTokenPayload {
    const decoded = this.jwt.verify<SupplierTokenPayload>(token);
    if (decoded.kind !== 'supplier-portal') {
      throw new Error('INVALID_TOKEN_KIND');
    }
    return decoded;
  }
}
