import {
  Entity,
  Property,
  ManyToOne,
  Enum,
  OneToMany,
  Collection,
  Unique,
  Index,
} from '@mikro-orm/core';
import { BaseTenantEntity } from '../../../common/entities/base-tenant.entity';
import { ProductVariant } from '../../products/entities/product-variant.entity';
import { Tenant } from '../../tenants/entities/tenant.entity';
import { Warehouse } from '../../definitions/entities/warehouse.entity';
import { WarehouseLocation } from '../../definitions/entities/warehouse-location.entity';
import { Currency } from '../../definitions/entities/currency.entity';
import { Partner } from '../../partners/entities/partner.entity';

export enum InventoryItemStatus {
  IN_STOCK = 'IN_STOCK',
  RESERVED = 'RESERVED',
  SOLD = 'SOLD',
  CONSUMED = 'CONSUMED',
  LOST = 'LOST',
  WASTE = 'WASTE',
  // ── Textile-specific kartela lifecycle (Sprint 1) ──
  FULL = 'FULL', // Full roll, never cut
  PARTIAL = 'PARTIAL', // Cut at least once, still has inventory
  ALLOCATED = 'ALLOCATED', // Child kartela reserved for specific SO line
  QUARANTINED = 'QUARANTINED', // Damaged or failed QC, set aside from sale
}

/**
 * Shade variation type — color tone consistency within a roll.
 *
 * - `CS` = Center-to-Side variation (different tone in center vs edges)
 * - `SS` = Side-to-Side variation (tone differs between the two edges)
 * - `NONE` = Homogeneous color, no detectable shade variation
 */
export enum ShadeVariation {
  CS = 'CS',
  SS = 'SS',
  NONE = 'NONE',
}

/**
 * Stok Kalemi / Top (Inventory Item / Roll) - CORE ENTITY
 *
 * Tekstil ERP'nin kalbi. Her fiziksel top kumaş, benzersiz bir barkodla izlenen tekil bir varlıktır.
 * Standart e-ticaret mantığından (product.stock_qty) tamamen farklıdır.
 *
 * Senaryo: 50m'lik bir top (R1) var. Müşteri 10m istedi.
 * 1. R1'den 10m rezerve edilir (reservedQuantity += 10)
 * 2. Kesim onaylandığında: currentQuantity = 40m, InventoryTransaction kaydı oluşur
 *
 * Nerede kullanılır: WMS stok listesi, sipariş rulo seçimi, mal kabul, kesim, sevkiyat
 */
@Entity({ tableName: 'inventory_items' })
@Unique({ properties: ['tenant', 'barcode'] })
export class InventoryItem extends BaseTenantEntity {
  @ManyToOne(() => ProductVariant)
  variant!: ProductVariant;

  @Property()
  @Index()
  barcode!: string;

  /**
   * Textile kartela (sample card) number — format: KRT-YYYY-MMDD-SEQ
   * Distinct from `barcode` (generic) — specific to textile roll traceability.
   * Unique per tenant. Generated by KartelaGeneratorService.
   */
  @Property({ nullable: true })
  @Index()
  kartelaNumber?: string;

  /**
   * Parent kartela ID for cut children.
   * When a roll is split via `InventoryService.splitRoll()`, the new
   * sub-roll references the original via this field. Null for original rolls.
   */
  @Property({ nullable: true })
  @Index()
  parentKartelaId?: string;

  @Property({ nullable: true })
  @Index()
  batchCode?: string; // Lot/Parti numarası (renk farkı yönetimi için kritik)

  // ─── Miktar Yönetimi ──────────────────────────────────────

  /**
   * Initial roll length when first received — immutable after creation.
   * Represents the ORIGINAL top/roll length in the roll's unit (metre/kg).
   * Used for "full vs partial" classification and top-equivalent calculations.
   */
  @Property({ type: 'decimal', precision: 10, scale: 2 })
  initialQuantity!: number;

  @Property({ type: 'decimal', precision: 10, scale: 2 })
  currentQuantity!: number; // Remaining metres (23.40m)

  @Property({ type: 'decimal', precision: 10, scale: 2, default: 0 })
  reservedQuantity: number = 0; // Reserved for orders (not yet cut)

  // availableQuantity = currentQuantity - reservedQuantity (computed, not persisted)

  // ─── Shade & Lot Grouping (Sprint 1) ──────────────────────

  /** Shade group identifier within a lot (e.g., "A1", "A2") */
  @Property({ nullable: true })
  @Index()
  shadeGroup?: string;

  /** Color tone variation type within the roll */
  @Enum({ items: () => ShadeVariation, nullable: true })
  shadeVariation?: ShadeVariation;

  /** Reference color code for this shade group */
  @Property({ nullable: true })
  shadeReference?: string;

  // ─── GSM (Gramaj) Tracking (Sprint 1) ─────────────────────

  /** Measured GSM at goods receive (grams per square metre) */
  @Property({ type: 'decimal', precision: 8, scale: 2, nullable: true })
  actualGSM?: number;

  /** GSM variance percent vs ProductVariant.standardGSM (signed) */
  @Property({ type: 'decimal', precision: 5, scale: 2, nullable: true })
  gsmVariance?: number;

  // ─── Konum ────────────────────────────────────────────────

  @ManyToOne(() => Warehouse, { nullable: true })
  warehouse?: Warehouse;

  @ManyToOne(() => WarehouseLocation, { nullable: true })
  location?: WarehouseLocation;

  // ─── Maliyet ve Kaynak ────────────────────────────────────

  @Property({ type: 'decimal', precision: 10, scale: 2, nullable: true })
  costPrice?: number; // Birim maliyeti (metre başına)

  @ManyToOne(() => Currency, { nullable: true })
  costCurrency?: Currency;

  @ManyToOne(() => Partner, { nullable: true })
  receivedFrom?: Partner; // Hangi tedarikçiden geldi

  @Property({ nullable: true, type: 'datetime' })
  receivedAt?: Date; // Depoya giriş tarihi

  // ─── Mal Kabul Referansı ──────────────────────────────────

  @Property({ nullable: true })
  goodsReceiveId?: string; // GoodsReceive FK (string olarak, circular dep önlemek için)

  // ─── Durum ────────────────────────────────────────────────

  @Enum(() => InventoryItemStatus)
  status: InventoryItemStatus = InventoryItemStatus.IN_STOCK;

  @Property({ nullable: true, type: 'datetime' })
  expiresAt?: Date; // Son kullanma (bazı kumaşlar için)

  // ─── İşlemler ─────────────────────────────────────────────

  @OneToMany('InventoryTransaction', 'item')
  transactions = new Collection<object>(this);

  constructor(
    variant: ProductVariant,
    tenant: Tenant,
    barcode: string,
    quantity: number,
  ) {
    super();
    this.variant = variant;
    this.tenant = tenant;
    this.barcode = barcode;
    this.initialQuantity = quantity;
    this.currentQuantity = quantity;
  }
}
