import { Entity, Property, ManyToOne, Enum, Index } from '@mikro-orm/core';
import { BaseTenantEntity } from '../../../common/entities/base-tenant.entity';
import { Fair } from './fair.entity';
import { LeadSource } from './lead-source.entity';
import { Partner } from '../../partners/entities/partner.entity';
import { User } from '../../users/entities/user.entity';

/**
 * Lead kanban stages. Matches the 4-column frontend board.
 */
export enum LeadStage {
  NEW = 'NEW',
  QUALIFIED = 'QUALIFIED',
  PROPOSAL = 'PROPOSAL',
  WON = 'WON',
  LOST = 'LOST',
}

/**
 * Lead — a prospective customer, typically generated by a FairParticipant
 * handover or a web form. `convertedPartner` links to the Partner row
 * created on WON conversion.
 */
@Entity({ tableName: 'leads' })
export class Lead extends BaseTenantEntity {
  @Property()
  @Index()
  fullName!: string;

  @Property({ nullable: true })
  company?: string;

  @Property({ nullable: true })
  email?: string;

  @Property({ nullable: true })
  phone?: string;

  @ManyToOne(() => LeadSource, { nullable: true })
  source?: LeadSource;

  @ManyToOne(() => Fair, { nullable: true })
  fair?: Fair;

  @Enum(() => LeadStage)
  @Index()
  stage: LeadStage = LeadStage.NEW;

  @Property({ nullable: true, type: 'decimal', precision: 14, scale: 2 })
  estimatedValue?: number;

  @Property({ nullable: true })
  currency?: string;

  @ManyToOne(() => User, { nullable: true })
  owner?: User;

  @ManyToOne(() => Partner, { nullable: true })
  convertedPartner?: Partner;

  @Property({ nullable: true, type: 'datetime' })
  convertedAt?: Date;

  @Property({ nullable: true, type: 'text' })
  notes?: string;
}
